/**
 * The service worker, generated by Workbox after the pages are written.
 *
 * `docs/PLAN.md` Phase 6 settled the two decisions this file implements, and it
 * settled them "up front, because they are cheap now and expensive later". Both
 * are constraints rather than preferences, so they are restated here where the
 * code is.
 *
 * **PRECACHE THE SHELL, NEVER THE PAGES.** `apps/srd` — the precedent this
 * migration copies — globs `**` + `/*.{js,css,woff2,svg}` and deliberately
 * excludes HTML, with no navigation fallback. Optfall has **13,675 pages**, so
 * here it is not a preference at all: precaching them would mean shipping the
 * whole site to every visitor's disk on first load. Visited pages get
 * `StaleWhileRevalidate` and nothing else is promised.
 *
 * **AND THERE IS NO `navigateFallback`, WHICH IS THE HALF WORTH SPELLING OUT.**
 * The tempting configuration serves a cached shell for any unmatched navigation,
 * so the app "works offline" everywhere. On this site that would be a lie with a
 * specific shape: an unvisited card URL would resolve, offline, to a page that
 * renders the wrong card's shell or an empty one, when the honest answer is that
 * the page is not here. A reference tool that answers confidently and wrongly is
 * worse than one that says it does not know.
 *
 * **CARD IMAGES ARE NEVER CACHED.** `docs/COMPLIANCE.md` §5 — the licence to
 * display LSS's art is revocable, and a service worker that has already stored
 * the art is a cache we cannot recall. That is why the rule below is an explicit
 * `NetworkOnly` on the image host rather than the mere absence of a rule:
 * "nothing matches it today" is an accident away from becoming false, and this
 * one has to fail closed. Faces stay network-fetched, and losing them offline
 * costs a rendering layer exactly as "Survive revocation" says it should.
 */

import { generateSW } from "workbox-build";

import { FACE_HOST } from "../src/lib/faces";

/**
 * The host every card face is served from, written as a LITERAL inside the
 * matcher below — and this paragraph is the reason, because the obvious spelling
 * is broken in a way that builds cleanly and fails silently.
 *
 * **A `urlPattern` callback is serialized with `Function.prototype.toString`.**
 * Workbox writes the function's SOURCE TEXT into `sw.js`; the closure does not
 * come with it. So a matcher that referenced a module-scope `IMAGE_HOST`
 * constant emitted `({url}) => url.hostname === IMAGE_HOST` into a worker where
 * that identifier does not exist. Every request threw a `ReferenceError` inside
 * route matching, which aborted matching entirely — so the image guard never ran
 * AND the page cache below never ran either. The build was green, the worker
 * registered and activated, and the precache populated correctly. The only
 * visible symptom was that the `pages` cache stayed empty.
 *
 * The literal cannot be interpolated in — it sits inside a function body that is
 * read as text. So it is written out, and `assertHostMatches` checks it against
 * `FACE_HOST` on every build, which is what stops the two from drifting.
 */
const IMAGE_HOST = "optfall-images.netlify.app";

/** The shape Workbox passes a `urlPattern` callback. */
interface RouteMatchArgs {
  readonly request: Request;
  readonly url: URL;
  readonly sameOrigin: boolean;
}

export interface ServiceWorkerResult {
  readonly precached: number;
  readonly bytes: number;
}

/**
 * The literal in the matcher still names the host `faces.ts` serves from.
 *
 * Cheap, and it is the only thing standing between "one source of truth" and two
 * strings that happen to agree today.
 */
function assertHostMatches(): void {
  const expected = new URL(FACE_HOST).hostname;
  if (expected === IMAGE_HOST) return;

  throw new Error(
    `The service worker's NetworkOnly rule names "${IMAGE_HOST}" but FACE_HOST is "${expected}". ` +
      `docs/COMPLIANCE.md §5 forbids caching card art, and a rule pointing at the wrong host enforces nothing. ` +
      `Update the literal inside the urlPattern callback in this file — it cannot read a constant, see the note above it.`,
  );
}

/**
 * The emitted worker really contains the rules this file described.
 *
 * THIS EXISTS BECAUSE THE FAILURE IT CATCHES ALREADY HAPPENED. A serialized
 * callback that references anything from its closure emits a worker that throws
 * at match time — green build, registered worker, populated precache, and two
 * dead routes. Reading the output back is the only place that is visible.
 */
function assertRoutesEmitted(source: string): void {
  const problems: string[] = [];

  if (!source.includes(IMAGE_HOST)) {
    problems.push(
      `the NetworkOnly rule for ${IMAGE_HOST} is missing — card art could be cached, which docs/COMPLIANCE.md §5 forbids`,
    );
  }
  if (!source.includes('"pages"')) {
    problems.push("the StaleWhileRevalidate page cache is missing");
  }
  /* The specific shape of the bug: an identifier that existed only in the
     TypeScript module, left dangling in the emitted worker. */
  if (/[^."\w]IMAGE_HOST\b/.test(source)) {
    problems.push(
      "a matcher references IMAGE_HOST, which is not defined in the worker — the callback closed over a constant its serialization does not carry",
    );
  }

  if (problems.length > 0) {
    throw new Error(
      `The generated service worker is wrong:\n  ${problems.join("\n  ")}`,
    );
  }
}

export async function writeServiceWorker(
  outDir: string,
): Promise<ServiceWorkerResult> {
  assertHostMatches();

  const { count, size, warnings } = await generateSW({
    globDirectory: outDir,
    /*
     * THE SHELL, AND NOTHING THAT IS A PAGE OR A PICTURE. `webmanifest` is here
     * because an installed app that cannot read its own manifest offline is not
     * installed in any useful sense; `svg` covers the mark in both its forms.
     * `html` is absent on purpose and `webp`/`png`/`jpg` are absent twice over —
     * once for size, once for the licence.
     */
    globPatterns: ["**/*.{js,css,woff2,svg,webmanifest}"],
    swDest: `${outDir}/sw.js`,
    /*
     * A new worker takes over as soon as it is installed rather than waiting
     * for every tab to close. The shipped assets are content-hashed, so there
     * is no version-skew hazard in doing so — and the alternative is a reader
     * who updates the site and keeps being served the old shell until they
     * quit the browser.
     */
    skipWaiting: true,
    clientsClaim: true,
    /* Old precaches from a previous deploy are deleted rather than left to
       occupy quota that the page cache below could be using. */
    cleanupOutdatedCaches: true,
    runtimeCaching: [
      {
        /*
         * NEVER, AND FIRST IN THE LIST. Rules are evaluated in order, so the
         * prohibition is stated before anything that could broaden into it.
         */
        urlPattern: ({ url }: { url: URL }) =>
          url.hostname === "optfall-images.netlify.app",
        handler: "NetworkOnly",
      },
      {
        /*
         * VISITED PAGES, AND ONLY VISITED ONES. `StaleWhileRevalidate` serves
         * the stored copy instantly and refreshes it behind the reader, which
         * is the right trade for a corpus that resyncs on a schedule rather
         * than continuously: a card page that is a day stale is still correct
         * about the card, and the legality data states its own confirmation
         * date on the page.
         *
         * Same-origin navigations only. A cross-origin navigation is somebody
         * leaving.
         */
        urlPattern: ({ request, sameOrigin }: RouteMatchArgs) =>
          sameOrigin && request.mode === "navigate",
        handler: "StaleWhileRevalidate",
        options: {
          cacheName: "pages",
          /*
           * A ceiling, because there are 13,675 pages and a determined browse
           * would otherwise store all of them. 200 is generous for the reading
           * this cache exists to serve — the deck you are building, the cards
           * you just looked up — and small enough that it cannot become an
           * accidental mirror of the site.
           */
          expiration: { maxEntries: 200, purgeOnQuotaError: true },
        },
      },
    ],
  });

  for (const warning of warnings) console.warn(`[sw] ${warning}`);

  assertRoutesEmitted(await Bun.file(`${outDir}/sw.js`).text());

  return { precached: count, bytes: size };
}
