/**
 * The service worker, generated by Workbox after the pages are written.
 *
 * `docs/PLAN.md` Phase 6 settled the two decisions this file implements, and it
 * settled them "up front, because they are cheap now and expensive later". Both
 * are constraints rather than preferences, so they are restated here where the
 * code is.
 *
 * **PRECACHE THE SHELL, NEVER THE PAGES.** `apps/srd` — the precedent this
 * migration copies — globs `**` + `/*.{js,css,woff2,svg}` and deliberately
 * excludes HTML, with no navigation fallback. Optfall has **13,675 pages**, so
 * here it is not a preference at all: precaching them would mean shipping the
 * whole site to every visitor's disk on first load. Visited pages get
 * `NetworkFirst` — network when there is one, cache when there is not — and
 * nothing else is promised.
 *
 * **AND THE PAGE CACHE IS EMPTIED ON EVERY DEPLOY**, via `sw-purge.js`. Stored
 * HTML links content-hashed assets, so it stops being renderable the moment a
 * deploy replaces them; a new worker activating is the exact signal that has
 * happened. Without that, both the offline path and the network timeout below
 * can hand a reader a page that cannot paint.
 *
 * **AND THERE IS NO `navigateFallback`, WHICH IS THE HALF WORTH SPELLING OUT.**
 * The tempting configuration serves a cached shell for any unmatched navigation,
 * so the app "works offline" everywhere. On this site that would be a lie with a
 * specific shape: an unvisited card URL would resolve, offline, to a page that
 * renders the wrong card's shell or an empty one, when the honest answer is that
 * the page is not here. A reference tool that answers confidently and wrongly is
 * worse than one that says it does not know.
 *
 * **CARD IMAGES ARE NEVER CACHED.** `docs/COMPLIANCE.md` §5 — the licence to
 * display LSS's art is revocable, and a service worker that has already stored
 * the art is a cache we cannot recall. That is why the rule below is an explicit
 * `NetworkOnly` on the image host rather than the mere absence of a rule:
 * "nothing matches it today" is an accident away from becoming false, and this
 * one has to fail closed. Faces stay network-fetched, and losing them offline
 * costs a rendering layer exactly as "Survive revocation" says it should.
 */

import { generateSW } from "workbox-build";

import { FACE_HOST } from "../src/lib/faces";

/**
 * The host every card face is served from, written as a LITERAL inside the
 * matcher below — and this paragraph is the reason, because the obvious spelling
 * is broken in a way that builds cleanly and fails silently.
 *
 * **A `urlPattern` callback is serialized with `Function.prototype.toString`.**
 * Workbox writes the function's SOURCE TEXT into `sw.js`; the closure does not
 * come with it. So a matcher that referenced a module-scope `IMAGE_HOST`
 * constant emitted `({url}) => url.hostname === IMAGE_HOST` into a worker where
 * that identifier does not exist. Every request threw a `ReferenceError` inside
 * route matching, which aborted matching entirely — so the image guard never ran
 * AND the page cache below never ran either. The build was green, the worker
 * registered and activated, and the precache populated correctly. The only
 * visible symptom was that the `pages` cache stayed empty.
 *
 * The literal cannot be interpolated in — it sits inside a function body that is
 * read as text. So it is written out, and `assertHostMatches` checks it against
 * `FACE_HOST` on every build, which is what stops the two from drifting.
 */
const IMAGE_HOST = "optfall-images.netlify.app";

/** The shape Workbox passes a `urlPattern` callback. */
interface RouteMatchArgs {
  readonly request: Request;
  readonly url: URL;
  readonly sameOrigin: boolean;
}

export interface ServiceWorkerResult {
  readonly precached: number;
  readonly bytes: number;
}

/**
 * The literal in the matcher still names the host `faces.ts` serves from.
 *
 * Cheap, and it is the only thing standing between "one source of truth" and two
 * strings that happen to agree today.
 */
function assertHostMatches(): void {
  const expected = new URL(FACE_HOST).hostname;
  if (expected === IMAGE_HOST) return;

  throw new Error(
    `The service worker's NetworkOnly rule names "${IMAGE_HOST}" but FACE_HOST is "${expected}". ` +
      `docs/COMPLIANCE.md §5 forbids caching card art, and a rule pointing at the wrong host enforces nothing. ` +
      `Update the literal inside the urlPattern callback in this file — it cannot read a constant, see the note above it.`,
  );
}

/**
 * The emitted worker really contains the rules this file described.
 *
 * THIS EXISTS BECAUSE THE FAILURE IT CATCHES ALREADY HAPPENED. A serialized
 * callback that references anything from its closure emits a worker that throws
 * at match time — green build, registered worker, populated precache, and two
 * dead routes. Reading the output back is the only place that is visible.
 */
function assertRoutesEmitted(source: string): void {
  const problems: string[] = [];

  if (!source.includes(IMAGE_HOST)) {
    problems.push(
      `the NetworkOnly rule for ${IMAGE_HOST} is missing — card art could be cached, which docs/COMPLIANCE.md §5 forbids`,
    );
  }
  if (!source.includes('"pages"')) {
    problems.push("the NetworkFirst page cache is missing");
  }
  if (!source.includes("sw-purge.js")) {
    problems.push(
      "the page-cache purge is not imported — without it a document cached before a deploy outlives the hashed assets it links, and both the offline path and the network timeout can serve it",
    );
  }
  /* The specific shape of the bug: an identifier that existed only in the
     TypeScript module, left dangling in the emitted worker. */
  if (/[^."\w]IMAGE_HOST\b/.test(source)) {
    problems.push(
      "a matcher references IMAGE_HOST, which is not defined in the worker — the callback closed over a constant its serialization does not carry",
    );
  }

  if (problems.length > 0) {
    throw new Error(
      `The generated service worker is wrong:\n  ${problems.join("\n  ")}`,
    );
  }
}

export async function writeServiceWorker(
  outDir: string,
): Promise<ServiceWorkerResult> {
  assertHostMatches();

  /*
   * Hashed from the file's own bytes, so a deploy that changes the door
   * invalidates the precached copy and one that does not leaves it alone. A
   * constant here would pin readers to the first version they ever cached.
   */
  const startUrlRevision = Bun.hash(
    await Bun.file(`${outDir}/index.html`).text(),
  ).toString(16);

  const { count, size, warnings } = await generateSW({
    globDirectory: outDir,
    /*
     * THE SHELL, AND NOTHING THAT IS A PAGE OR A PICTURE. `webmanifest` is here
     * because an installed app that cannot read its own manifest offline is not
     * installed in any useful sense; `svg` covers the mark in both its forms.
     * `html` is absent on purpose and `webp`/`png`/`jpg` are absent twice over —
     * once for size, once for the licence.
     */
    globPatterns: ["**/*.{js,css,woff2,svg,webmanifest}"],
    /*
     * Three lines Workbox has no hook for: drop the page cache whenever a new
     * worker activates. See `serviceWorkerPurge` in `ssg/assets.ts` for why that
     * is the deploy signal and why the page cache is unsafe without it.
     */
    importScripts: ["/sw-purge.js"],
    /*
     * ONE DOCUMENT, AND IT IS THE ONE THE MANIFEST NAMES. `start_url` is `/`,
     * so an installed app launched offline would otherwise open on the
     * browser's network error — an install that does not survive its own first
     * cold start.
     *
     * THE URL HAS NO TRAILING SLASH BEYOND THE ROOT, and that detail is the
     * whole difference between working and not. Workbox's precache matcher
     * appends `directoryIndex` only when the REQUEST path already ends in `/`,
     * so an entry written `/search/` is never matched by a navigation to
     * `/search` — it is precached bytes nothing reaches, while the cold start it
     * was added for still falls through to the network route and errors. That
     * is exactly what the first version of this did, and the browser check that
     * "proved" it worked had navigated to `/search/` by hand.
     *
     * This does not weaken "never precache the pages". It is a single file
     * chosen because it is the app's entry point, not a category; the other
     * 13,674 remain the runtime cache's business.
     */
    additionalManifestEntries: [{ url: "/", revision: startUrlRevision }],
    swDest: `${outDir}/sw.js`,
    /*
     * A new worker takes over as soon as it is installed rather than waiting
     * for every tab to close. The shipped assets are content-hashed, so there
     * is no version-skew hazard in doing so — and the alternative is a reader
     * who updates the site and keeps being served the old shell until they
     * quit the browser.
     */
    skipWaiting: true,
    clientsClaim: true,
    /* Old precaches from a previous deploy are deleted rather than left to
       occupy quota that the page cache below could be using. */
    cleanupOutdatedCaches: true,
    runtimeCaching: [
      {
        /*
         * NEVER, AND FIRST IN THE LIST. Rules are evaluated in order, so the
         * prohibition is stated before anything that could broaden into it.
         */
        urlPattern: ({ url }: { url: URL }) =>
          url.hostname === "optfall-images.netlify.app",
        handler: "NetworkOnly",
      },
      {
        /*
         * VISITED PAGES, AND ONLY VISITED ONES.
         *
         * `NetworkFirst`, NOT `StaleWhileRevalidate`, AND THE DIFFERENCE IS A
         * BUG RATHER THAN A PREFERENCE. Every stylesheet and script this site
         * serves is content-hashed, and Netlify's deploys are atomic — so the
         * previous deploy's `/assets/*-<oldhash>.css` stops existing the moment
         * a new one lands.
         *
         * Under `StaleWhileRevalidate` a returning reader is served the STORED
         * HTML first, which links exactly those dead URLs: they 404, they are
         * not in the new precache either, and the page paints unstyled with no
         * hydrated islands until the background revalidation finishes and the
         * reader navigates a second time. Every returning reader, every deploy.
         *
         * `NetworkFirst` asks the network first and falls back to the cache
         * only when it cannot answer — which is the offline story this rule
         * exists for, unchanged, without ever serving a document that has
         * outlived its assets. The cost is a network round trip on a warm
         * navigation, and that is the correct thing to pay for it.
         *
         * Same-origin navigations only. A cross-origin navigation is somebody
         * leaving.
         */
        urlPattern: ({ request, sameOrigin }: RouteMatchArgs) =>
          sameOrigin && request.mode === "navigate",
        handler: "NetworkFirst",
        options: {
          cacheName: "pages",
          /*
           * LIE-FI IS THE CASE THIS EXISTS FOR. `NetworkFirst` with no timeout
           * waits for the fetch to settle, and a connected-but-dead network
           * never settles quickly — so a reader with a cached copy of the page
           * they are opening would sit on a blank screen rather than see it.
           *
           * IT IS ONLY SAFE BECAUSE OF THE PURGE. A timeout falls back to the
           * cache, which is the same thing being offline does, so on its own it
           * reopens the deploy-staleness failure `NetworkFirst` was chosen to
           * close: a slow response on a page cached before the current deploy
           * would serve HTML linking assets that no longer exist. `sw-purge.js`
           * empties this cache whenever a new worker activates, so there is no
           * pre-deploy entry left to fall back to and the timeout can only ever
           * return a document from the deploy that is live.
           *
           * Three seconds is longer than any real response to this static site
           * and shorter than anybody's patience.
           */
          networkTimeoutSeconds: 3,
          /*
           * A ceiling, because there are 13,675 pages and a determined browse
           * would otherwise store all of them. 200 is generous for the reading
           * this cache exists to serve — the deck you are building, the cards
           * you just looked up — and small enough that it cannot become an
           * accidental mirror of the site.
           */
          expiration: { maxEntries: 200, purgeOnQuotaError: true },
        },
      },
    ],
  });

  for (const warning of warnings) console.warn(`[sw] ${warning}`);

  assertRoutesEmitted(await Bun.file(`${outDir}/sw.js`).text());

  return { precached: count, bytes: size };
}
